# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for Tlon MCP Server
FROM node:lts-alpine
# Create app directory
WORKDIR /usr/src/app
# Install dependencies
COPY package.json .
RUN npm install --production --ignore-scripts
# Copy source files
COPY index.js .
# Default transport is stdio; expose port if HTTP used
EXPOSE 3001
# Start the server
CMD ["npm", "start"]
